package com.jeepclub.backend.shared.authorization;

public enum PermissionCode {

    // AUTHENTICATION / USERS
    AUTHENTICATION_USER_READ,
    AUTHENTICATION_USER_CREATE,
    AUTHENTICATION_USER_UPDATE,
    AUTHENTICATION_USER_DISABLE,
    AUTHENTICATION_USER_ENABLE,
    AUTHENTICATION_USER_PASSWORD_RESET_LINK_GENERATE,
    AUTHENTICATION_USER_TEMPORARY_PASSWORD_GENERATE,

    // AUTHENTICATION / PASSWORD RECOVERY
    AUTHENTICATION_PASSWORD_RECOVERY_READ,
    AUTHENTICATION_PASSWORD_RECOVERY_CANCEL,

    // AUTHENTICATION / REFRESH TOKENS
    AUTHENTICATION_REFRESH_TOKEN_READ,
    AUTHENTICATION_REFRESH_TOKEN_REVOKE,

    // AUTHENTICATION / SESSIONS
    AUTHENTICATION_SESSION_READ,
    AUTHENTICATION_SESSION_LOGOUT,

    // AUTHORIZATION / ROLES
    AUTHORIZATION_ROLE_READ,
    AUTHORIZATION_ROLE_CREATE,
    AUTHORIZATION_ROLE_UPDATE,
    AUTHORIZATION_ROLE_DISABLE,
    AUTHORIZATION_ROLE_ENABLE,
    AUTHORIZATION_ROLE_DELETE,

    // AUTHORIZATION / PERMISSIONS
    AUTHORIZATION_PERMISSION_READ,
    AUTHORIZATION_PERMISSION_ASSIGN,
    AUTHORIZATION_PERMISSION_REVOKE,

    // AUTHORIZATION / USER ROLES
    AUTHORIZATION_USER_ROLE_READ,
    AUTHORIZATION_USER_ROLE_ASSIGN,
    AUTHORIZATION_USER_ROLE_REVOKE,

    // BILLING / CHARGE ASSIGNMENTS
    BILLING_CHARGE_ASSIGNMENT_CREATE,
    BILLING_CHARGE_ASSIGNMENT_READ,
    BILLING_CHARGE_ASSIGNMENT_UPDATE,

    // BILLING / CHARGE CYCLES
    BILLING_CHARGE_CYCLE_GENERATE,
    BILLING_CHARGE_CYCLE_READ,
    BILLING_CHARGE_CYCLE_CANCEL,
    BILLING_CHARGE_CYCLE_FINISH,
    BILLING_CHARGE_CYCLE_ARCHIVE,

    // BILLING / CHARGE DEFINITIONS
    BILLING_CHARGE_DEFINITION_CREATE,
    BILLING_CHARGE_DEFINITION_READ,
    BILLING_CHARGE_DEFINITION_UPDATE,

    // BILLING / MEMBER CHARGES
    BILLING_MEMBER_CHARGE_READ,
    BILLING_MEMBER_CHARGE_UPDATE,
    BILLING_MEMBER_CHARGE_CANCEL,

    // BILLING / PAYMENTS
    BILLING_PAYMENT_READ,
    BILLING_PAYMENT_CONFIRM,
    BILLING_PAYMENT_REJECT,

    // BILLING / REFUNDS
    BILLING_REFUND_READ,
    BILLING_REFUND_APPROVE,
    BILLING_REFUND_REJECT,
    BILLING_REFUND_MARK_AS_REFUNDED,
    BILLING_REFUND_EXPIRE,
    BILLING_REFUND_CANCEL,

    // DEPENDENTS
    DEPENDENTS_DEPENDENT_READ,

    // HEALTH
    HEALTH_MEDICAL_PROFILE_UPDATE,
    HEALTH_MEDICAL_PROFILE_READ,

    // MEMBERSHIP / MEMBERSHIP REQUESTS
    MEMBERSHIP_MEMBERSHIP_REQUEST_READ,
    MEMBERSHIP_MEMBERSHIP_REQUEST_APPROVE,
    MEMBERSHIP_MEMBERSHIP_REQUEST_REJECT,
    MEMBERSHIP_MEMBERSHIP_APPLICANT_BLOCK,
    MEMBERSHIP_MEMBERSHIP_APPLICANT_UNBLOCK,
    MEMBERSHIP_MEMBERSHIP_REQUEST_INVITE_RESEND,

    // VEHICLES
    VEHICLES_VEHICLE_INCLUDE,
    VEHICLES_VEHICLE_READ,
    VEHICLES_VEHICLE_UPDATE,
    VEHICLES_VEHICLE_DELETE
}
