package com.jeepclub.backend.shared.authorization;

public enum PermissionCode {

    // IDENTITY / USERS
    IDENTITY_USER_READ,
    IDENTITY_USER_CREATE,
    IDENTITY_USER_UPDATE,
    IDENTITY_USER_DISABLE,
    IDENTITY_USER_ENABLE,

    // AUTHENTICATION / CREDENTIALS
    AUTHENTICATION_USER_PASSWORD_RESET_LINK_GENERATE,
    AUTHENTICATION_USER_TEMPORARY_PASSWORD_GENERATE,

    // AUTHENTICATION / PASSWORD RECOVERY
    AUTHENTICATION_PASSWORD_RECOVERY_READ,
    AUTHENTICATION_PASSWORD_RECOVERY_CANCEL,

    // AUTHENTICATION / REFRESH TOKENS
    AUTHENTICATION_REFRESH_TOKEN_READ,
    AUTHENTICATION_REFRESH_TOKEN_REVOKE,

    // AUTHENTICATION / SESSIONS
    AUTHENTICATION_SESSION_READ,
    AUTHENTICATION_SESSION_LOGOUT,

    // AUTHORIZATION / ROLES
    AUTHORIZATION_ROLE_READ,
    AUTHORIZATION_ROLE_CREATE,
    AUTHORIZATION_ROLE_UPDATE,
    AUTHORIZATION_ROLE_DISABLE,
    AUTHORIZATION_ROLE_ENABLE,
    AUTHORIZATION_ROLE_DELETE,

    // AUTHORIZATION / PERMISSIONS
    AUTHORIZATION_PERMISSION_READ,
    AUTHORIZATION_PERMISSION_ASSIGN,
    AUTHORIZATION_PERMISSION_REVOKE,

    // AUTHORIZATION / USER ROLES
    AUTHORIZATION_USER_ROLE_READ,
    AUTHORIZATION_USER_ROLE_ASSIGN,
    AUTHORIZATION_USER_ROLE_REVOKE,

    // BILLING / CHARGE ASSIGNMENTS
    BILLING_CHARGE_ASSIGNMENT_CREATE,
    BILLING_CHARGE_ASSIGNMENT_READ,
    BILLING_CHARGE_ASSIGNMENT_UPDATE,

    // BILLING / CHARGE CYCLES
    BILLING_CHARGE_CYCLE_GENERATE,
    BILLING_CHARGE_CYCLE_READ,
    BILLING_CHARGE_CYCLE_CANCEL,
    BILLING_CHARGE_CYCLE_FINISH,
    BILLING_CHARGE_CYCLE_ARCHIVE,

    // BILLING / CHARGE DEFINITIONS
    BILLING_CHARGE_DEFINITION_CREATE,
    BILLING_CHARGE_DEFINITION_READ,
    BILLING_CHARGE_DEFINITION_UPDATE,

    // BILLING / MEMBER CHARGES
    BILLING_MEMBER_CHARGE_READ,
    BILLING_MEMBER_CHARGE_UPDATE,
    BILLING_MEMBER_CHARGE_CANCEL,

    // BILLING / PAYMENTS
    BILLING_PAYMENT_READ,
    BILLING_PAYMENT_CONFIRM,
    BILLING_PAYMENT_REJECT,

    // BILLING / REFUNDS
    BILLING_REFUND_READ,
    BILLING_REFUND_APPROVE,
    BILLING_REFUND_REJECT,
    BILLING_REFUND_MARK_AS_REFUNDED,
    BILLING_REFUND_EXPIRE,
    BILLING_REFUND_CANCEL,

    // DEPENDENTS
    DEPENDENTS_DEPENDENT_READ,

    // HEALTH
    HEALTH_MEDICAL_PROFILE_UPDATE,
    HEALTH_MEDICAL_PROFILE_READ,
    HEALTH_MEDICAL_PROFILE_DELETE,

    // MEMBERSHIP / MEMBERSHIP REQUESTS
    MEMBERSHIP_MEMBERSHIP_REQUEST_READ,
    MEMBERSHIP_MEMBERSHIP_REQUEST_APPROVE,
    MEMBERSHIP_MEMBERSHIP_REQUEST_REJECT,
    MEMBERSHIP_MEMBERSHIP_APPLICANT_BLOCK,
    MEMBERSHIP_MEMBERSHIP_APPLICANT_UNBLOCK,
    MEMBERSHIP_MEMBERSHIP_REQUEST_INVITE_RESEND,
    MEMBERSHIP_BILLING_CONFIGURATION_READ,
    MEMBERSHIP_BILLING_CONFIGURATION_UPDATE,

    // TOOLS
    TOOLS_TOOL_CREATE,
    TOOLS_TOOL_READ,
    TOOLS_TOOL_UPDATE,
    TOOLS_TOOL_DELETE,
    TOOLS_TOOL_ACTIVATE,
    TOOLS_TOOL_DEACTIVATE,

    // VEHICLES
    VEHICLES_VEHICLE_CREATE,
    VEHICLES_VEHICLE_READ,
    VEHICLES_VEHICLE_UPDATE,
    VEHICLES_VEHICLE_DELETE,

    PUBLICATIONS_EVENT_CREATE,
    PUBLICATIONS_EVENT_READ,
    PUBLICATIONS_EVENT_READ_ADMIN,
    PUBLICATIONS_EVENT_UPDATE,
    PUBLICATIONS_EVENT_PUBLISH,
    PUBLICATIONS_EVENT_CANCEL,
    PUBLICATIONS_EVENT_FINISH,
    PUBLICATIONS_EVENT_DELETE,
    PUBLICATIONS_EVENT_REGISTER,
    PUBLICATIONS_EVENT_REGISTRATION_READ,
    PUBLICATIONS_EVENT_REGISTRATION_CANCEL,
    PUBLICATIONS_EVENT_GUEST_REQUEST_CREATE,
    PUBLICATIONS_EVENT_GUEST_REQUEST_READ,
    PUBLICATIONS_EVENT_GUEST_ADMIN_CREATE,
    PUBLICATIONS_EVENT_GUEST_ADMIN_READ,
    PUBLICATIONS_EVENT_GUEST_APPROVE,
    PUBLICATIONS_EVENT_GUEST_REJECT,
    PUBLICATIONS_EVENT_RIDE_OFFER_READ,
    PUBLICATIONS_EVENT_RIDE_OFFER_RESPOND,
    PUBLICATIONS_EVENT_RIDE_OFFER_SELECT,
    PUBLICATIONS_EVENT_ADMIN_DASHBOARD_READ,
    PUBLICATIONS_EVENT_HEALTH_EMERGENCY_READ,

    // PUBLICATIONS / NOTICE
    PUBLICATIONS_INTERACTION_LIKE,
    PUBLICATIONS_COMMENT_CREATE,
    PUBLICATIONS_COMMENT_READ,
    PUBLICATIONS_FEED_READ,
    PUBLICATIONS_PUBLICATION_READ,
    PUBLICATIONS_NOTICE_CREATE,
    PUBLICATIONS_NOTICE_READ,
    PUBLICATIONS_NOTICE_UPDATE,
    PUBLICATIONS_NOTICE_PUBLISH,
    PUBLICATIONS_NOTICE_ARCHIVE,
    PUBLICATIONS_NOTICE_DELETE,

    // PUBLICATIONS / SERVICE
    PUBLICATIONS_SERVICE_REQUEST_CREATE,
    PUBLICATIONS_SERVICE_REQUEST_READ,
    PUBLICATIONS_SERVICE_REQUEST_ADMIN_READ,
    PUBLICATIONS_SERVICE_REQUEST_APPROVE,
    PUBLICATIONS_SERVICE_REQUEST_REJECT,
    PUBLICATIONS_SERVICE_CHANGE_REQUEST_CREATE,
    PUBLICATIONS_SERVICE_CHANGE_REQUEST_READ,
    PUBLICATIONS_SERVICE_CHANGE_REQUEST_ADMIN_READ,
    PUBLICATIONS_SERVICE_CHANGE_REQUEST_APPROVE,
    PUBLICATIONS_SERVICE_CHANGE_REQUEST_REJECT,
    PUBLICATIONS_SERVICE_READ,
    PUBLICATIONS_SERVICE_DELETE,
    PUBLICATIONS_SERVICE_ADMIN_READ,
    PUBLICATIONS_SERVICE_ADMIN_DELETE
}
