spring.application.name=backend

# Conexão com o seu banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/jeep_club?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=craft123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# AQUI ESTÁ A DICA DO LUCAS:
# Isso faz o Hibernate criar as tabelas automaticamente baseado nas suas Entidades
spring.jpa.hibernate.ddl-auto=update

# Opcional: Mostra os comandos SQL no terminal para você ver o banco sendo criado
spring.jpa.show-sql=true

# Vamos desligar o Flyway temporariamente para ele não brigar com o Hibernate
spring.flyway.enabled=false