spring.application.name=backend
spring.config.import=optional:file:./jwt-secrets.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/jeepclub_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

security.jwt.issuer=jeep-club-backend
security.jwt.access-token-expiration-minutes=15
security.jwt.refresh-token-expiration-days=7
