package com.jeepclub.backend.authorization.core.domain.enums;

public enum PermissionCode {

    // AUTHENTICATION / USERS
    AUTHENTICATION_USER_READ,
    AUTHENTICATION_USER_CREATE,
    AUTHENTICATION_USER_UPDATE,
    AUTHENTICATION_USER_DISABLE,
    AUTHENTICATION_USER_ENABLE,

    // AUTHORIZATION / ROLES
    AUTHORIZATION_ROLE_READ,
    AUTHORIZATION_ROLE_CREATE,
    AUTHORIZATION_ROLE_UPDATE,
    AUTHORIZATION_ROLE_DELETE,

    // AUTHORIZATION / PERMISSIONS
    AUTHORIZATION_PERMISSION_READ,
    AUTHORIZATION_PERMISSION_ASSIGN,
    AUTHORIZATION_PERMISSION_REVOKE,

    // AUTHORIZATION / USER ROLES
    AUTHORIZATION_USER_ROLE_ASSIGN,
    AUTHORIZATION_USER_ROLE_REVOKE
}