package com.jeepclub.backend.billing.infra.persistence.query;
import com.jeepclub.backend.billing.core.repository.BillingExportQuery;
import com.jeepclub.backend.billing.core.application.query.BillingExportFilter;
import com.jeepclub.backend.billing.core.domain.model.MemberCharge;
import com.jeepclub.backend.shared.export.*;
import java.time.*;
import java.math.BigDecimal;
@org.springframework.stereotype.Repository @lombok.RequiredArgsConstructor
public class BillingExportJpaQuery implements BillingExportQuery {
    private final jakarta.persistence.EntityManager em;
    public java.util.Map<Long,ExportRow> latestPayments(java.util.Collection<Long> chargeIds) {
        if(chargeIds.isEmpty())return java.util.Map.of();
        var result=new java.util.HashMap<Long,ExportRow>();
        em.createQuery("select p.memberChargeId,p.id,p.amount,p.paymentMethod,p.status,p.submittedAt from MemberPaymentEntity p where p.memberChargeId in :ids and p.id=(select max(latest.id) from MemberPaymentEntity latest where latest.memberChargeId=p.memberChargeId)",Object[].class)
            .setParameter("ids",chargeIds).getResultList().forEach(t->result.put((Long)t[0],ExportRow.of(t[1],t[2],t[3],t[4],t[5])));
        return result;
    }
    public boolean exists(Product product,Long id) {
        String entity=switch(product){case DEFINITIONS->"ChargeDefinitionEntity";case CYCLES->"ChargeCycleEntity";case CHARGES->"MemberChargeEntity";case PAYMENTS->"MemberPaymentEntity";case REFUNDS->"MemberRefundEntity";};
        return em.createQuery("select count(e) from "+entity+" e where e.id=:id",Long.class).setParameter("id",id).getSingleResult()>0;
    }
    public java.util.List<Entry> read(Product p,BillingExportFilter f,int offset) {
        return switch(p) {case DEFINITIONS-> definitions(f,offset);case CYCLES-> cycles(f,offset);case CHARGES-> charges(f,offset);case PAYMENTS-> payments(f,offset);case REFUNDS-> refunds(f,offset);};
    }
    private java.util.List<Entry> definitions(BillingExportFilter f,int offset) {
        return em.createQuery("select e.id,e.name,e.description,e.defaultAmount,e.recurrenceType,e.required,e.paymentAcceptancePolicy,e.latePaymentGraceDays,e.status,e.createdAt,e.updatedAt,e.archivedAt,a.id,case when type(a)=AllMembersChargeAssignmentEntity then 'Todos os membros' when type(a)=UserChargeAssignmentEntity then 'Usuário' when type(a)=RoleChargeAssignmentEntity then 'Papel de acesso' when type(a)=EventParticipantsChargeAssignmentEntity then 'Participantes de evento' else 'Sem atribuição' end,a.active,a.createdAt,a.updatedAt,coalesce(treat(a as UserChargeAssignmentEntity).userId,treat(a as RoleChargeAssignmentEntity).roleId,treat(a as EventParticipantsChargeAssignmentEntity).eventId),treat(a as UserChargeAssignmentEntity).userId,treat(a as RoleChargeAssignmentEntity).roleId,treat(a as EventParticipantsChargeAssignmentEntity).eventId from ChargeDefinitionEntity e left join ChargeAssignmentEntity a on a.chargeDefinitionId=e.id where (:id is null or e.id=:id) and (:recurrence is null or cast(e.recurrenceType as string)=:recurrence) and (:status is null or cast(e.status as string)=:status) and (:chargeDefinitionId is null or e.id=:chargeDefinitionId) and (:userId is null or treat(a as UserChargeAssignmentEntity).userId=:userId) and (:eventId is null or treat(a as EventParticipantsChargeAssignmentEntity).eventId=:eventId) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id,a.id",Object[].class).setParameter("id",f.id()).setParameter("recurrence",f.recurrence()).setParameter("status",f.status()).setParameter("chargeDefinitionId",f.chargeDefinitionId()).setParameter("userId",f.userId()).setParameter("eventId",f.eventId()).setParameter("from",f.from()).setParameter("to",f.to()).setFirstResult(offset).setMaxResults(ExportPages.CHUNK)
            .getResultList().stream().map(t->new Entry((Long)t[18],(Long)t[19],(Long)t[20],null,ExportRow.of(java.util.Arrays.copyOf(t,18)))).toList();
    }
    private java.util.List<Entry> cycles(BillingExportFilter f,int offset) {
        return em.createQuery("select e.id,e.chargeDefinitionId,e.chargeDefinitionNameSnapshot,e.chargeDefinitionDescriptionSnapshot,e.chargeDefinitionDefaultAmountSnapshot,e.chargeDefinitionRecurrenceTypeSnapshot,e.chargeDefinitionRequiredSnapshot,e.chargeDefinitionPaymentAcceptancePolicySnapshot,e.chargeDefinitionLatePaymentGraceDaysSnapshot,e.code,e.dueDate,e.status,e.generatedByUserId,e.generatedAt,e.canceledAt,e.canceledByUserId,e.finishedAt,e.finishedByUserId,e.archivedAt,e.archivedByUserId,e.createdAt,e.updatedAt,null,null,ctx.eventId from ChargeCycleEntity e left join EventChargeContextEntity ctx on ctx.cycleId=e.id where (:id is null or e.id=:id) and (:chargeDefinitionId is null or e.chargeDefinitionId=:chargeDefinitionId) and (:chargeCycleId is null or e.id=:chargeCycleId) and (:status is null or cast(e.status as string)=:status) and (:eventId is null or ctx.eventId=:eventId) and (:recurrence is null or cast(e.chargeDefinitionRecurrenceTypeSnapshot as string)=:recurrence) and (:year is null or year(e.dueDate)=:year) and (:month is null or month(e.dueDate)=:month) and (:dueFrom is null or e.dueDate>=:dueFrom) and (:dueTo is null or e.dueDate<=:dueTo) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id",Object[].class).setParameter("id",f.id()).setParameter("chargeDefinitionId",f.chargeDefinitionId()).setParameter("chargeCycleId",f.chargeCycleId()).setParameter("status",f.status()).setParameter("eventId",f.eventId()).setParameter("recurrence",f.recurrence()).setParameter("year",f.year()).setParameter("month",f.month()).setParameter("dueFrom",f.dueFrom()).setParameter("dueTo",f.dueTo()).setParameter("from",f.from()).setParameter("to",f.to()).setFirstResult(offset).setMaxResults(ExportPages.CHUNK)
            .getResultList().stream().map(t->new Entry((Long)t[22],(Long)t[23],(Long)t[24],null,ExportRow.of(java.util.Arrays.copyOf(t,22)))).toList();
    }
    private java.util.List<Entry> charges(BillingExportFilter f,int offset) {
        return em.createQuery("select e.id,e.userId,e.chargeDefinitionId,e.chargeCycleId,e.originalAmount,e.finalAmount,e.dueDate,e.paymentAcceptancePolicy,e.latePaymentGraceDays,e.paymentAllowedUntil,e.status,e.createdAt,e.updatedAt,e.paidAt,e.canceledAt,cy.chargeDefinitionNameSnapshot,cy.code,cy.chargeDefinitionRecurrenceTypeSnapshot,year(cy.dueDate),month(cy.dueDate),ctx.eventId,e.userId,null,ctx.eventId,e.id,e.userId,e.chargeDefinitionId,e.chargeCycleId,e.originalAmount,e.finalAmount,e.dueDate,e.paymentAcceptancePolicy,e.latePaymentGraceDays,e.paymentAllowedUntil,e.status,e.createdAt,e.updatedAt,e.paidAt,e.canceledAt from MemberChargeEntity e join ChargeCycleEntity cy on cy.id=e.chargeCycleId left join EventChargeContextEntity ctx on ctx.cycleId=cy.id where (:id is null or e.id=:id) and (:userId is null or e.userId=:userId) and (:chargeDefinitionId is null or e.chargeDefinitionId=:chargeDefinitionId) and (:chargeCycleId is null or e.chargeCycleId=:chargeCycleId) and (:status is null or cast(e.status as string)=:status) and (:chargeStatus is null or cast(e.status as string)=:chargeStatus) and (:eventId is null or ctx.eventId=:eventId) and (:recurrence is null or cast(cy.chargeDefinitionRecurrenceTypeSnapshot as string)=:recurrence) and (:year is null or year(cy.dueDate)=:year) and (:month is null or month(cy.dueDate)=:month) and (:dueFrom is null or cy.dueDate>=:dueFrom) and (:dueTo is null or cy.dueDate<=:dueTo) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id",Object[].class).setParameter("id",f.id()).setParameter("userId",f.userId()).setParameter("chargeDefinitionId",f.chargeDefinitionId()).setParameter("chargeCycleId",f.chargeCycleId()).setParameter("status",f.status()).setParameter("chargeStatus",f.chargeStatus()).setParameter("eventId",f.eventId()).setParameter("recurrence",f.recurrence()).setParameter("year",f.year()).setParameter("month",f.month()).setParameter("dueFrom",f.dueFrom()).setParameter("dueTo",f.dueTo()).setParameter("from",f.from()).setParameter("to",f.to()).setFirstResult(offset).setMaxResults(ExportPages.CHUNK)
            .getResultList().stream().map(t->new Entry((Long)t[21],(Long)t[22],(Long)t[23],MemberCharge.reconstitute((Long)t[24],(Long)t[25],(Long)t[26],(Long)t[27],(BigDecimal)t[28],(BigDecimal)t[29],(LocalDate)t[30],(com.jeepclub.backend.billing.core.domain.enums.cycle.PaymentAcceptancePolicy)t[31],(Integer)t[32],(LocalDate)t[33],(com.jeepclub.backend.billing.core.domain.enums.charge.MemberChargeStatus)t[34],(Instant)t[35],(Instant)t[36],(Instant)t[37],(Instant)t[38]),ExportRow.of(java.util.Arrays.copyOf(t,21)))).toList();
    }
    private java.util.List<Entry> payments(BillingExportFilter f,int offset) {
        return em.createQuery("select e.id,e.memberChargeId,e.amount,e.paymentMethod,e.status,e.paidAt,e.confirmedAt,e.confirmedByUserId,e.rejectedAt,e.rejectedByUserId,e.rejectionReason,e.canceledAt,e.notes,e.createdAt,e.updatedAt,e.submittedAt,c.userId,c.chargeDefinitionId,c.chargeCycleId,cy.chargeDefinitionNameSnapshot,cy.code,cy.chargeDefinitionRecurrenceTypeSnapshot,year(cy.dueDate),month(cy.dueDate),ctx.eventId,c.dueDate,c.userId,null,ctx.eventId,c.id,c.userId,c.chargeDefinitionId,c.chargeCycleId,c.originalAmount,c.finalAmount,c.dueDate,c.paymentAcceptancePolicy,c.latePaymentGraceDays,c.paymentAllowedUntil,c.status,c.createdAt,c.updatedAt,c.paidAt,c.canceledAt from MemberPaymentEntity e join MemberChargeEntity c on c.id=e.memberChargeId join ChargeCycleEntity cy on cy.id=c.chargeCycleId left join EventChargeContextEntity ctx on ctx.cycleId=cy.id where (:id is null or e.id=:id) and (:userId is null or c.userId=:userId) and (:chargeDefinitionId is null or c.chargeDefinitionId=:chargeDefinitionId) and (:chargeCycleId is null or c.chargeCycleId=:chargeCycleId) and (:status is null or cast(e.status as string)=:status) and (:chargeStatus is null or cast(c.status as string)=:chargeStatus) and (:paymentMethod is null or cast(e.paymentMethod as string)=:paymentMethod) and (:eventId is null or ctx.eventId=:eventId) and (:recurrence is null or cast(cy.chargeDefinitionRecurrenceTypeSnapshot as string)=:recurrence) and (:year is null or year(cy.dueDate)=:year) and (:month is null or month(cy.dueDate)=:month) and (:dueFrom is null or cy.dueDate>=:dueFrom) and (:dueTo is null or cy.dueDate<=:dueTo) and (:from is null or e.submittedAt>=:from) and (:to is null or e.submittedAt<=:to) order by e.id",Object[].class).setParameter("id",f.id()).setParameter("userId",f.userId()).setParameter("chargeDefinitionId",f.chargeDefinitionId()).setParameter("chargeCycleId",f.chargeCycleId()).setParameter("status",f.status()).setParameter("chargeStatus",f.chargeStatus()).setParameter("paymentMethod",f.paymentMethod()).setParameter("eventId",f.eventId()).setParameter("recurrence",f.recurrence()).setParameter("year",f.year()).setParameter("month",f.month()).setParameter("dueFrom",f.dueFrom()).setParameter("dueTo",f.dueTo()).setParameter("from",f.from()).setParameter("to",f.to()).setFirstResult(offset).setMaxResults(ExportPages.CHUNK)
            .getResultList().stream().map(t->new Entry((Long)t[26],(Long)t[27],(Long)t[28],MemberCharge.reconstitute((Long)t[29],(Long)t[30],(Long)t[31],(Long)t[32],(BigDecimal)t[33],(BigDecimal)t[34],(LocalDate)t[35],(com.jeepclub.backend.billing.core.domain.enums.cycle.PaymentAcceptancePolicy)t[36],(Integer)t[37],(LocalDate)t[38],(com.jeepclub.backend.billing.core.domain.enums.charge.MemberChargeStatus)t[39],(Instant)t[40],(Instant)t[41],(Instant)t[42],(Instant)t[43]),ExportRow.of(java.util.Arrays.copyOf(t,26)))).toList();
    }
    private java.util.List<Entry> refunds(BillingExportFilter f,int offset) {
        return em.createQuery("select e.id,e.memberChargeId,e.memberPaymentId,e.chargeCycleId,e.userId,e.amount,e.reason,e.status,e.eligibleAt,e.eligibleUntil,e.createdByUserId,e.requestedAt,e.requestedByUserId,e.approvedAt,e.approvedByUserId,e.rejectedAt,e.rejectedByUserId,e.rejectionReason,e.refundedAt,e.refundedByUserId,e.canceledAt,e.canceledByUserId,e.createdAt,e.updatedAt,c.chargeDefinitionId,cy.chargeDefinitionNameSnapshot,cy.code,cy.chargeDefinitionRecurrenceTypeSnapshot,year(cy.dueDate),month(cy.dueDate),ctx.eventId,pay.amount,c.userId,null,ctx.eventId,c.id,c.userId,c.chargeDefinitionId,c.chargeCycleId,c.originalAmount,c.finalAmount,c.dueDate,c.paymentAcceptancePolicy,c.latePaymentGraceDays,c.paymentAllowedUntil,c.status,c.createdAt,c.updatedAt,c.paidAt,c.canceledAt from MemberRefundEntity e join MemberChargeEntity c on c.id=e.memberChargeId join ChargeCycleEntity cy on cy.id=c.chargeCycleId left join EventChargeContextEntity ctx on ctx.cycleId=cy.id left join MemberPaymentEntity pay on pay.id=e.memberPaymentId where (:id is null or e.id=:id) and (:userId is null or c.userId=:userId) and (:chargeDefinitionId is null or c.chargeDefinitionId=:chargeDefinitionId) and (:chargeCycleId is null or c.chargeCycleId=:chargeCycleId) and (:status is null or cast(e.status as string)=:status) and (:chargeStatus is null or cast(c.status as string)=:chargeStatus) and (:eventId is null or ctx.eventId=:eventId) and (:recurrence is null or cast(cy.chargeDefinitionRecurrenceTypeSnapshot as string)=:recurrence) and (:year is null or year(cy.dueDate)=:year) and (:month is null or month(cy.dueDate)=:month) and (:dueFrom is null or cy.dueDate>=:dueFrom) and (:dueTo is null or cy.dueDate<=:dueTo) and (:from is null or e.requestedAt>=:from) and (:to is null or e.requestedAt<=:to) order by e.id",Object[].class).setParameter("id",f.id()).setParameter("userId",f.userId()).setParameter("chargeDefinitionId",f.chargeDefinitionId()).setParameter("chargeCycleId",f.chargeCycleId()).setParameter("status",f.status()).setParameter("chargeStatus",f.chargeStatus()).setParameter("eventId",f.eventId()).setParameter("recurrence",f.recurrence()).setParameter("year",f.year()).setParameter("month",f.month()).setParameter("dueFrom",f.dueFrom()).setParameter("dueTo",f.dueTo()).setParameter("from",f.from()).setParameter("to",f.to()).setFirstResult(offset).setMaxResults(ExportPages.CHUNK)
            .getResultList().stream().map(t->new Entry((Long)t[32],(Long)t[33],(Long)t[34],MemberCharge.reconstitute((Long)t[35],(Long)t[36],(Long)t[37],(Long)t[38],(BigDecimal)t[39],(BigDecimal)t[40],(LocalDate)t[41],(com.jeepclub.backend.billing.core.domain.enums.cycle.PaymentAcceptancePolicy)t[42],(Integer)t[43],(LocalDate)t[44],(com.jeepclub.backend.billing.core.domain.enums.charge.MemberChargeStatus)t[45],(Instant)t[46],(Instant)t[47],(Instant)t[48],(Instant)t[49]),ExportRow.of(java.util.Arrays.copyOf(t,32)))).toList();
    }
}
