package com.jeepclub.backend.publications.infra.persistence.query;
import com.jeepclub.backend.publications.core.repository.PublicationExportQuery;
import com.jeepclub.backend.shared.export.*;
import java.time.Instant;
@org.springframework.stereotype.Repository @lombok.RequiredArgsConstructor
public class PublicationExportJpaQuery implements PublicationExportQuery {
    private final jakarta.persistence.EntityManager em;
    public java.util.Map<Long,String> ruleSummaries(java.util.Collection<Long> eventIds) {
        if(eventIds.isEmpty())return java.util.Map.of();
        var rows=em.createQuery("select r.eventId,r.chargeDefinitionId,r.requiredForParticipation,r.participationCutoff,r.financialDueDate from EventChargeRuleEntity r where r.eventId in :ids order by r.eventId,r.id",Object[].class)
            .setParameter("ids",eventIds).setMaxResults(20001).getResultList();
        if(rows.size()>20000)throw new ExportException(ExportException.Reason.LIMIT);
        var result=new java.util.HashMap<Long,String>();
        for(var r:rows)result.merge((Long)r[0],"Cobrança "+r[1]+"; obrigatória: "+ExportValues.text(r[2])+"; limite de participação: "+ExportValues.text(r[3])+"; vencimento: "+ExportValues.text(r[4]),(a,b)->a+" | "+b);
        return result;
    }
    public java.util.List<Entry> read(Product p,Long id,String status,String lifecycle,Instant from,Instant to,Instant now,int offset) {
        return switch(p) {
case NOTICES -> em.createQuery("select e.id,e.authorUserId,e.title,e.content,e.status,e.createdAt,e.updatedAt,e.publishedAt,e.archivedAt from NoticeEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case NOTICE_HISTORY -> em.createQuery("select e.id,e.authorUserId,e.title,e.content,e.status,e.createdAt,e.updatedAt,e.publishedAt,e.archivedAt,e.publicationId,e.deletedByUserId,e.deletedAt from NoticeHistoryEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case SERVICES -> em.createQuery("select e.id,e.authorUserId,e.title,e.content,e.status,e.createdAt,e.updatedAt,e.publishedAt,e.archivedAt,e.sourceRequestId,e.amount,e.contactPhone from ServicePublicationEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case SERVICE_HISTORY -> em.createQuery("select e.id,e.authorUserId,e.title,e.content,e.status,e.createdAt,e.updatedAt,e.publishedAt,e.archivedAt,e.publicationId,e.deletedByUserId,e.deletedAt,e.sourceRequestId,e.amount,e.contactPhone from ServicePublicationHistoryEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.createdAt>=:from) and (:to is null or e.createdAt<=:to) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case EVENTS -> em.createQuery("select e.id,e.authorUserId,e.title,e.content,e.status,e.createdAt,e.updatedAt,e.publishedAt,e.archivedAt,e.startsAt,e.endsAt,e.eventStatus,case when cast(e.eventStatus as string)='CANCELLED' then 'CANCELLED' when cast(e.eventStatus as string)='FINISHED' or (e.endsAt is not null and e.endsAt<=:now) then 'FINISHED' when e.startsAt>:now then 'OPEN' else 'IN_PROGRESS' end from EventEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.startsAt>=:from) and (:to is null or e.startsAt<=:to) and (:lifecycle is null or (case when cast(e.eventStatus as string)='CANCELLED' then 'CANCELLED' when cast(e.eventStatus as string)='FINISHED' or (e.endsAt is not null and e.endsAt<=:now) then 'FINISHED' when e.startsAt>:now then 'OPEN' else 'IN_PROGRESS' end)=:lifecycle) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to).setParameter("now",now).setParameter("lifecycle",lifecycle)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case EVENT_HISTORY -> em.createQuery("select e.id,e.authorUserId,e.title,e.content,e.status,e.createdAt,e.updatedAt,e.publishedAt,e.archivedAt,e.publicationId,e.deletedByUserId,e.deletedAt,e.startsAt,e.endsAt,e.eventStatus,case when cast(e.eventStatus as string)='CANCELLED' then 'CANCELLED' when cast(e.eventStatus as string)='FINISHED' or (e.endsAt is not null and e.endsAt<=:now) then 'FINISHED' when e.startsAt>:now then 'OPEN' else 'IN_PROGRESS' end from EventHistoryEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.startsAt>=:from) and (:to is null or e.startsAt<=:to) and (:lifecycle is null or (case when cast(e.eventStatus as string)='CANCELLED' then 'CANCELLED' when cast(e.eventStatus as string)='FINISHED' or (e.endsAt is not null and e.endsAt<=:now) then 'FINISHED' when e.startsAt>:now then 'OPEN' else 'IN_PROGRESS' end)=:lifecycle) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to).setParameter("now",now).setParameter("lifecycle",lifecycle)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case SERVICE_REQUESTS -> em.createQuery("select e.id,e.requestedByUserId,e.title,e.content,e.amount,e.contactPhone,e.status,e.rejectionReason,e.reviewedByUserId,e.createdPublicationId,e.requestedAt,e.reviewedAt,e.updatedAt from ServicePublicationRequestEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.requestedAt>=:from) and (:to is null or e.requestedAt<=:to) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[1],ExportRow.of(t))).toList();
case CHANGE_REQUESTS -> em.createQuery("select e.id,e.servicePublicationId,e.requestedByUserId,e.proposedTitle,e.proposedContent,e.proposedAmount,e.proposedContactPhone,e.status,e.rejectionReason,e.reviewedByUserId,e.requestedAt,e.reviewedAt,e.updatedAt from ServicePublicationChangeRequestEntity e where (:id is null or e.id=:id) and (:status is null or cast(e.status as string)=:status) and (:from is null or e.requestedAt>=:from) and (:to is null or e.requestedAt<=:to) order by e.id",Object[].class).setParameter("id",id).setParameter("status",status).setParameter("from",from).setParameter("to",to)
            .setFirstResult(offset).setMaxResults(ExportPages.CHUNK).getResultList().stream().map(t->new Entry((Long)t[2],ExportRow.of(t))).toList();
        };
    }
}
